config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show] 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'hello#index'
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"
    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  
  has_many :posts, dependent: :destroy 
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 

  mount_uploader :image, ImageUploader

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_post
    before_action :authenticate_user!
    def create
        post = Post.find(params[:post_id])
        comment = post.comments.build(comment_params) #buildを使い、contentとpost_idの二つを同時に代入
        comment.user_id = current_user.id
        if comment.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path)
        else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path)
        end
    end
    def destroy
        @comment = Comment.find(params[:id])
        if @comment.destroy
            redirect_to post_path(@post)
        else   
            render post_path(@post)
        end
    end
    private
        def set_post
            @post = Post.find(params[:post_id])
        end
        def comment_params
            params.require(:comment).permit(:content)
        end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController

    def index
    end
    def link
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(post_id: params[:post_id])
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!

    def index
        @post = Post.new
        @posts = Post.all
        if params[:search]  != nil && params[:search] != ''
            search = params[:search]
            @posts = Post.joins(:user).where("about LIKE ? OR name LIKE ?", "%#{search}%", "%#{search}%")
        else
            @posts = Post.all
        end
    end

    def new
        @post = Post.new
    end

    def create
        post = Post.new(post_params)
        post.user_id = current_user.id
        if post.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def show
        @post = Post.find(params[:id])
        @comments = @post.comments
        @comment = Comment.new
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        post = Post.find(params[:id])
        if post.update(post_params)
            redirect_to :action => "show", :id => post.id
        else
            redirect_to :action => "new"
        end
    end

    def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to action: :index
    end

    private
    def post_params
        params.require(:post).permit(:image,:about)
    end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
        @user = User.find(params[:relationship][:following_id])
        current_user.follow!(@user)
        redirect_to @user
    end
    
    def destroy
        @user = Relationship.find(params[:id]).following
        current_user.unfollow!(@user)
        redirect_to @user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
    
    def following
        @user = User.find(params[:id])
        @users = @user.followings
        render 'show_follow'
    end

    def followers
        @user = User.find(params[:id])
        @users = @user.followers
        render 'show_follower'
    end

    private

    def user_params
    params.require(:user).permit(:image) 
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user?(user)
        user == current_user
    end
end

app/views/hello/index.html.erb
top page
<%= link_to "ログイン", posts_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geekinstagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div clas="edit-container">
    <%= form_for @post do |f| %>
        <p><%= f.label :image %></p>
        <p><%= f.file_field :image %></p>
        <p><%= f.label :about %></p>
        <p><%= f.text_field :about %></p>
        <%= f.submit "編集する" %>
    <% end %>

</div>

app/views/posts/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
    <head><!--ページに表示されない情報(サイトの裏側の設定)-->
        <meta charset="utf-8">
        <title>投稿一覧</title><!--ブラウザのタブのタイトルを指定-->
    </head>

    <body>

    <div class="allpost">
        <h5>all posts</h5> 
    </div>
    <div class="search">
        <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
        <%= text_field_tag :search %>
        <%= submit_tag 'search', class: "searchbtn" %>
        <% end %>
    </div>

    <%= link_to "新規投稿ページへ", new_post_path %>
    <% if user_signed_in? %>
    <%= link_to "マイページへ", user_path(current_user.id) %>　
    <% end %>
    <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
    
    <div class="posts-container">
      <div class="row">
        <% @posts.each do |t| %>
          <div class="col-sm-3 box">
            <div class="card" style="width: 255px; ">
              <div class="card-img-top">
                <%= image_tag t.image_url, size: "250x200" if t.image?  %>
              </div>

              <div class="card-body">
                <p class="card-text">
                  <a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
                  <p><%= t.about %></p>
                </p>
                

                <% if user_signed_in? %>
                  <% if current_user.already_liked?(t) %>
                    <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                      <i class="fas fa-heart"></i><%= t.likes.count %>
                    <% end %>
                  <% else %>
                    <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                      <i class="far fa-heart"></i><%= t.likes.count %>
                    <% end %>
                  <% end %>
                <% else %>
                  <i class="far fa-heart"></i><%= t.likes.count %>
                <% end %>
                
                    <%= link_to "To details", post_path(t.id), class: "link" %>
                    <% if user_signed_in? && current_user.id == t.user_id %>
                      <%= link_to "Try to edit", edit_post_path(t.id), class: "link" %>
                      <%= button_to "Delete", post_path(t.id), method: :delete %>
                    <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>


  </body>
</html>




app/views/posts/new.html.erb
<div class="title">
    <h1>GeekInstagram</h1>
    <h3>新規Post</h3>
</div>
<div class="postform">
    <%= form_for @post do |f| %>
        <div class="field">
            <p><%= f.label :image %></p>
            <p><%= f.file_field :image %></p>
            <p><%= f.label :about %></p>
            <p><%= f.text_field :about %></p>
        </div>
        <%= f.submit "Post" %>
    <% end %>
    <%= link_to "投稿一覧に戻る", posts_path %>
</div>

app/views/posts/show.html.erb
<div class="title">
    <h1>GeekInstagram</h1>
    <h3>Post詳細</h3>
</div>
<div class="postdetail">
    <p><%= image_tag @post.image_url, size: "250x200" if @post.image?  %></p>
    <p><%= @post.about %></p>
    <p><%= @post.user.email %></p>
    <p><%= @post.created_at %></p>

    <% if user_signed_in? %>
        <% if current_user.already_liked?(@post) %>
            <%= link_to post_like_path(@post), method: :delete do %>
                <i class="fas fa-heart"></i><%= @post.likes.count %>
            <% end %>
        <% else %>
            <%= link_to post_likes_path(@post), method: :post do %>
                <i class="fas fa-heart"></i><%= @post.likes.count %>
            <% end %>
        <% end %>
    <% else %>
        <i class="fas fa-heart"></i><%= @post.likes.count %>
    <% end %>
</div>
<div class="showlike">
    <h6>いいねしたユーザー</h6>
    <% @post.liked_users.each do |user| %>
        <li><%= user.email %></li>
    <% end %>
</div>

<div class="comment-wrapper">
    <h6>コメント一覧</h6>
    <% @comments.each do |c| %>
        <div>
            <%= c.user.email unless c.user.blank? %>
            <%= c.content %>
            <%= link_to "削除", post_comment_path(@post, c), method: :delete %>
        </div>
            <br>
    <% end %>

    <% if user_signed_in? %>
        <%= form_with(model: [@post, @comment], local: true) do |f| %>
            <%= f.text_area :content %>
            <%= button_tag type: "submit" do %>
                <i class="far fa-comments"></i> コメントする
            <% end %>
        <% end %>
    <% end %>
</div>

<%= link_to "投稿一覧に戻る", posts_path %>
<%= link_to "編集する", edit_post_path(@post.id) %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
    <div><%= f.hidden_field :following_id %></div>
    <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form">
    <% if current_user.following?(@user) %>
        <%= render 'unfollow' %>
    <% else %>
        <%= render 'follow' %>
    <% end %>
    </div>
<% end %>  

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
    <a href="<%= following_user_path(@user) %>">
        <strong id="following" class="stat">
            <%= @user.followings.count %>
        </strong>
        following
    </a>
    <a href="<%= followers_user_path(@user) %>">
        <strong id="followers" class="stat">
            <%= @user.followers.count %>
        </strong>
        followers
    </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<body>
    <h5 class="h5">ユーザー詳細</h5>
    <div class="user-image"><%= image_tag @user.image_url, class: "rounded-circle", size: "200x200" if @user.image?  %></div>
    <div class="profile">
        <% if current_user.id == @user.id %>
            <%= link_to "編集する", edit_user_registration_path %>
        <% end %>
        <p>名前 : <%= @user.name %></p>
        <p>メールアドレス : <%= @user.email %></p>
        <p>プロフィール : <%= @user.profile %></p>
        　　　<%= render 'follow_form' %>
        　　　<%= render 'stats' %>
    </div>
    <div class="user-post-container">
        <h5 class="h5">ユーザーの投稿一覧</h5>
        <div class="row">
            <% @user.posts.each do |t| %>
                <div class="col-sm-3 box">
                    <div class="card" style="width: 255px; ">
                        <%= image_tag t.image_url, size: "250x200" if t.image?  %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>

    <div class="user-likes-container">
        <h5 class="h5">ユーザーがいいねした投稿一覧</h5>
        <div class="row">
            <% @user.liked_posts.each do |t| %>
                <div class="col-sm-3 box">
                    <div class="card" style="width: 255px; ">
                        <%= image_tag t.image_url, size: "250x200" if t.image?  %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>


    

    <p><%= link_to "投稿一覧に戻る", posts_path %></p>
</body>

app/views/users/show_follow.html.erb
<div class="following-container">
    <% @user.followings.each do |user| %>
        <table>
        <tr>
            <td>  <%= user.name %> </td>
            <td><%= link_to '詳細', user_path(user) %></td>
        </tr>
        
        </table>
    <% end %>
</div>

app/views/users/show_follower.html.erb
<div class="folloer-container">
    <% @user.followers.each do |user| %>
    <table>
        <tr>
            <td>  <%= user.name %> </td>
            <td><%= link_to '詳細', user_path(user) %></td>
        </tr>

    </table>
    <% end %>
</div>